#!/usr/bin/env python3
"""Regenerate DaGym/Data/ExercisePhotoCatalog.swift from what is actually in
DaGym/Resources/ExercisePhotos.

Called by scripts/import-exercise-photos.sh (free-exercise-db pairs) and
scripts/import-exercise-photos-extra.py (wger / OpenTraining / Commons images); both write
.heic files into the folder and then let this script describe the folder. Every `<seedID>-0.heic`
is an exercise with photos; a `<seedID>-1.heic` beside it makes the pair that the hero
cross-fades, and its absence marks a single-frame exercise (shown still).

Usage:
    python3 scripts/lib/write-exercise-photo-catalog.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
PHOTOS = ROOT / "DaGym" / "Resources" / "ExercisePhotos"
CATALOG = ROOT / "DaGym" / "Data" / "ExercisePhotoCatalog.swift"


def pack(seed_ids: list[str]) -> str:
    """`|`-separated, wrapped to ~96 columns, four-space indented: one literal, not a 700-element
    collection literal that would blow the file-length limit and the type-checker's budget."""
    lines: list[str] = []
    current = ""
    for seed_id in seed_ids:
        candidate = seed_id if not current else f"{current}|{seed_id}"
        if len(candidate) > 96 and current:
            lines.append(current)
            current = seed_id
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(f"    {line}" for line in lines) or "    "


def main() -> None:
    names = set(os.listdir(PHOTOS))
    starts = sorted(name[:-7] for name in names if name.endswith("-0.heic"))
    singles = sorted(seed_id for seed_id in starts if f"{seed_id}-1.heic" not in names)
    orphans = sorted(name for name in names if name.endswith("-1.heic") and f"{name[:-7]}-0.heic" not in names)
    if orphans:
        print(f"error: end frames with no start frame: {orphans}", file=sys.stderr)
        sys.exit(1)

    source = f'''// Generated by scripts/lib/write-exercise-photo-catalog.py — do not edit by hand.
// Maps a seeded exercise's `seedID` to the photographs bundled for it in
// DaGym/Resources/ExercisePhotos: a start/end pair from free-exercise-db (yuhonas/free-exercise-db,
// Unlicense / public domain), or one or two frames from wger.de, OpenTraining or Wikimedia Commons
// (CC BY-SA / CC BY / public domain, credited per file in
// DaGym/Resources/ATTRIBUTION-ExercisePhotos.txt and on screen via `ExercisePhotoCredits`).

import Foundation

/// Looks up the bundled photographs for a seeded exercise, when we have any.
/// {len(starts)} of our seeded exercises have at least a start frame; {len(singles)} of those have no
/// end frame and are shown still. The rest return `nil` and callers (`ExercisePhotoView`) fall
/// back to the illustrated vector art or the body map.
///
/// Deliberately not an asset catalogue: these ship as plain files in a folder reference and are
/// loaded by path (see `ExercisePhotoStore`), because an .xcassets membership makes Xcode
/// rasterise every member at several scales and balloons `Assets.car`.
enum ExercisePhotoCatalog {{
    /// The bundle subdirectory the photos live in, relative to the app bundle root.
    static let bundleSubdirectory = "ExercisePhotos"

    /// Every seedID we ship photographs for.
    static let seedIDs: Set<String> = Set(
        packedSeedIDs.split(whereSeparator: {{ $0 == "|" || $0 == "\\n" }}).map(String.init)
    )

    /// The subset of `seedIDs` that has a start frame only — no `-1.heic`, so no cross-fade.
    static let singleFrameSeedIDs: Set<String> = Set(
        packedSingleFrameSeedIDs.split(whereSeparator: {{ $0 == "|" || $0 == "\\n" }}).map(String.init)
    )

    /// The photo resource names for `seedID` — start position first, end position second when
    /// there is one — or `nil` when this exercise has no photographs. Each name resolves to
    /// `<name>.heic` inside `bundleSubdirectory`.
    static func photoNames(for seedID: String) -> (start: String, end: String?)? {{
        guard seedIDs.contains(seedID) else {{ return nil }}
        let end = singleFrameSeedIDs.contains(seedID) ? nil : "\\(seedID)-1"
        return ("\\(seedID)-0", end)
    }}

    /// Existence check, mirroring `ExerciseArtCatalog.frames(for:)` so call sites read alike.
    static func hasPhotos(for seedID: String) -> Bool {{
        seedIDs.contains(seedID)
    }}

    /// seedIDs, `|`-separated and wrapped — one literal rather than a {len(starts)}-element
    /// collection literal, which would blow the file-length limit and the type-checker's budget.
    private static let packedSeedIDs = """
{pack(starts)}
    """

    private static let packedSingleFrameSeedIDs = """
{pack(singles)}
    """
}}
'''
    CATALOG.write_text(source)
    print(f"wrote {CATALOG} ({len(starts)} exercises, {len(singles)} single-frame)", file=sys.stderr)


if __name__ == "__main__":
    main()
