#!/usr/bin/env python3
"""Import the generated 3-frame line-art for exercises that have neither illustrated vector art
nor photographs.

The frames were generated for DaGym (Gemini 3.1 Flash Image via OpenRouter, September 2026),
styled after the Bryl Lim illustrations we already ship, and reviewed one by one before being
accepted; the project owns the output (see DaGym/Resources/ATTRIBUTION-ExerciseFrames.txt). The
source is a folder of grayscale PNGs named `<seedID>-{0,1,2}.png` — the start, middle and end of
the movement — plus an `accepted.json` whose keys are the seedIDs that passed review. Only
accepted exercises with all three frames are imported.

Each frame is written as DaGym/Resources/ExerciseFrames/<seedID>-<index>.heic: grayscale, 640 px
tall, HEIC quality 35 (about 10–14 KB a frame — the art is flat line work, so it survives heavy
compression). Then DaGym/Data/ExerciseFrameCatalog.swift is regenerated from what is actually in
the folder, the same way scripts/lib/write-exercise-photo-catalog.py describes ExercisePhotos.
Re-runnable: existing .heic files are only rewritten with --force, and the catalogue is always
rewritten so it never drifts from the folder.

Usage:
    python3 scripts/import-exercise-frames.py --source DIR [--accepted FILE] [--force]

`--accepted` defaults to `<source>/../final-accepted.json`. Needs macOS `sips` for HEIC.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRAMES = ROOT / "DaGym" / "Resources" / "ExerciseFrames"
CATALOG = ROOT / "DaGym" / "Data" / "ExerciseFrameCatalog.swift"

FRAME_COUNT = 3
HEIGHT = 640
QUALITY = 35
# Size ceiling per frame: a flat grayscale drawing at this height and quality is ~10–14 KB.
MAX_BYTES = 40 * 1024


def write_heic(source: Path, destination: Path) -> None:
    subprocess.run(
        [
            "sips", "-s", "format", "heic", "-s", "formatOptions", str(QUALITY), "-Z", str(HEIGHT),
            str(source), "--out", str(destination),
        ],
        check=True, capture_output=True,
    )
    size = destination.stat().st_size
    if size > MAX_BYTES:
        print(f"error: {destination.name} is {size // 1024} KB (> {MAX_BYTES // 1024} KB)", file=sys.stderr)
        sys.exit(1)


def pack(seed_ids: list[str]) -> str:
    """`|`-separated, wrapped to ~96 columns, four-space indented: one literal rather than a
    200-element collection literal that would strain the type-checker."""
    lines: list[str] = []
    current = ""
    for seed_id in seed_ids:
        candidate = seed_id if not current else f"{current}|{seed_id}"
        if len(candidate) > 96 and current:
            lines.append(current)
            current = seed_id
        else:
            current = candidate
    if current:
        lines.append(current)
    return "\n".join(f"    {line}" for line in lines) or "    "


def write_catalog() -> int:
    names = set(os.listdir(FRAMES)) if FRAMES.exists() else set()
    starts = sorted(name[:-7] for name in names if name.endswith("-0.heic"))
    incomplete = [s for s in starts if any(f"{s}-{i}.heic" not in names for i in range(FRAME_COUNT))]
    orphans = sorted(n for n in names if n.endswith(".heic") and n[:-7] not in starts)
    if incomplete or orphans:
        print(f"error: incomplete sets {incomplete}, orphan files {orphans}", file=sys.stderr)
        sys.exit(1)

    source = f'''// Generated by scripts/import-exercise-frames.py — do not edit by hand.
// Maps a seeded exercise's `seedID` to the generated 3-frame line-art bundled for it in
// DaGym/Resources/ExerciseFrames (start, middle and end of the movement, one grayscale HEIC
// each). Generated for DaGym and owned by the project — see
// DaGym/Resources/ATTRIBUTION-ExerciseFrames.txt.

import Foundation

/// Looks up the bundled generated frames for a seeded exercise, when we have them.
/// {len(starts)} of our seeded exercises have a set; every set is exactly `frameCount` frames. The
/// rest return `false` and callers (`ExerciseHeroMedia`) fall through to the photographs or the
/// body map. These only cover exercises with no illustrated vector art and no photographs, so
/// the hero's precedence (vector → frames → photo) never has to break a tie.
///
/// Not an asset catalogue, for the same reason as `ExercisePhotoCatalog`: plain files in a
/// folder reference, loaded by path (see `ExerciseFrameStore`).
enum ExerciseFrameCatalog {{
    /// The bundle subdirectory the frames live in, relative to the app bundle root.
    static let bundleSubdirectory = "ExerciseFrames"

    /// Frames per exercise: `<seedID>-0.heic` … `<seedID>-2.heic`.
    static let frameCount = {FRAME_COUNT}

    /// Every seedID we ship frames for.
    static let seedIDs: Set<String> = Set(
        packedSeedIDs.split(whereSeparator: {{ $0 == "|" || $0 == "\\n" }}).map(String.init)
    )

    /// Existence check, mirroring `ExercisePhotoCatalog.hasPhotos(for:)` so call sites read alike.
    static func hasFrames(for seedID: String) -> Bool {{
        seedIDs.contains(seedID)
    }}

    /// The resource names for `seedID`'s frames in movement order, or `nil` when it has none.
    /// Each resolves to `<name>.heic` inside `bundleSubdirectory`.
    static func frameNames(for seedID: String) -> [String]? {{
        guard seedIDs.contains(seedID) else {{ return nil }}
        return (0..<frameCount).map {{ "\\(seedID)-\\($0)" }}
    }}

    /// seedIDs, `|`-separated and wrapped — one literal rather than a {len(starts)}-element
    /// collection literal.
    private static let packedSeedIDs = """
{pack(starts)}
    """
}}
'''
    CATALOG.write_text(source)
    return len(starts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", type=Path, required=True, help="folder of <seedID>-{0,1,2}.png")
    parser.add_argument("--accepted", type=Path, help="JSON object whose keys are the accepted seedIDs")
    parser.add_argument("--force", action="store_true", help="rewrite .heic files that already exist")
    args = parser.parse_args()

    accepted_path = args.accepted or (args.source.parent / "final-accepted.json")
    accepted = sorted(json.loads(accepted_path.read_text()).keys())
    FRAMES.mkdir(parents=True, exist_ok=True)

    written = skipped = 0
    for seed_id in accepted:
        sources = [args.source / f"{seed_id}-{i}.png" for i in range(FRAME_COUNT)]
        if not all(p.exists() for p in sources):
            print(f"error: {seed_id} is accepted but not all {FRAME_COUNT} frames exist", file=sys.stderr)
            sys.exit(1)
        for index, source in enumerate(sources):
            destination = FRAMES / f"{seed_id}-{index}.heic"
            if destination.exists() and not args.force:
                skipped += 1
                continue
            write_heic(source, destination)
            written += 1

    count = write_catalog()
    total = sum(p.stat().st_size for p in FRAMES.glob("*.heic"))
    print(
        f"{written} frames written, {skipped} kept; {count} exercises in {CATALOG.name}; "
        f"{FRAMES.relative_to(ROOT)} is {total / 1024 / 1024:.1f} MB",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
