// Generated by scripts/import-exercise-frames.py — do not edit by hand.
// Maps a seeded exercise's `seedID` to the generated 3-frame line-art bundled for it in
// DaGym/Resources/ExerciseFrames (start, middle and end of the movement, one grayscale HEIC
// each). Generated for DaGym and owned by the project — see
// DaGym/Resources/ATTRIBUTION-ExerciseFrames.txt.

import Foundation

/// Looks up the bundled generated frames for a seeded exercise, when we have them.
/// 218 of our seeded exercises have a set; every set is exactly `frameCount` frames. The
/// rest return `false` and callers (`ExerciseHeroMedia`) fall through to the photographs or the
/// body map. These only cover exercises with no illustrated vector art and no photographs, so
/// the hero's precedence (vector → frames → photo) never has to break a tie.
///
/// Not an asset catalogue, for the same reason as `ExercisePhotoCatalog`: plain files in a
/// folder reference, loaded by path (see `ExerciseFrameStore`).
enum ExerciseFrameCatalog {
    /// The bundle subdirectory the frames live in, relative to the app bundle root.
    static let bundleSubdirectory = "ExerciseFrames"

    /// Frames per exercise: `<seedID>-0.heic` … `<seedID>-2.heic`.
    static let frameCount = 3

    /// Every seedID we ship frames for.
    static let seedIDs: Set<String> = Set(
        packedSeedIDs.split(whereSeparator: { $0 == "|" || $0 == "\n" }).map(String.init)
    )

    /// Existence check, mirroring `ExercisePhotoCatalog.hasPhotos(for:)` so call sites read alike.
    static func hasFrames(for seedID: String) -> Bool {
        seedIDs.contains(seedID)
    }

    /// The resource names for `seedID`'s frames in movement order, or `nil` when it has none.
    /// Each resolves to `<name>.heic` inside `bundleSubdirectory`.
    static func frameNames(for seedID: String) -> [String]? {
        guard seedIDs.contains(seedID) else { return nil }
        return (0..<frameCount).map { "\(seedID)-\($0)" }
    }

    /// seedIDs, `|`-separated and wrapped — one literal rather than a 218-element
    /// collection literal.
    private static let packedSeedIDs = """
    1_2_Kneeling_Thoracic_Rotation|3D_lunge_warmup|90_90_Breathing|90_90_Hip_Switches
    Abdominal_Draw_In|Abduction_while_standing|Adductor_Rock_Backs|Arabesque|Arch_Hang
    Archer_Pull_Up|Arm_Raises_T_Y_I|Arm_and_neck_stretch|Axe_Hold|Back_Lever|Back_bridge
    Back_neck_stretch|Backward_shoulder_rotation|Banded_Shoulder_Drills|Bear_crawl_pull_through
    Bent_Leg_Hamstring_Stretch|Bent_knee_Iron_Cross|Bent_over_Cable_Flye
    Bent_over_row_to_external_rotation|Bizeps_Curls_Trifecta|Black_Widow_Knee_Slides|Blackroll|Blaze
    Bobbing_Exhale_Drill|Bretzel_stretch|Bronco|Butchers_Block_Stretch|Cable_Press_Around
    Cable_Tri_Extension_Internal_Rotation|Calves_foam_roller|Cat_Plank|Chin_tuck|Clap_Push_UP
    Claps_over_the_head|Clockwise_neck_circles|Cool_Down_Swim|Copenhagen_Adduction_Exercise
    Core_Rotation|Couch_Stretch|Counterclockwise_neck_circles|Cross_Body_Cable_Y_Raise
    Curl_With_Shoulder_Elevated|Curl_with_kettlebell_two_hands|Deadhang
    Deep_breathing_standing_or_seated|Delt_Stretch|Devil_s_Press|Diaphragmatic_Breathing
    Doorway_Pectoral_Stretch|Double_Leg_Abdominal_Press|Dragon_squat|Drop_Curl|Dumbbell_Frog_Press
    Dumbbell_Shoulder_Rotations|Dumbbell_bicep_curl_to_press|Dynamic_side_hold
    Easy_Continuous_Swim_Freestyle|Elephant_Walks|Elevated_Hamstring_Stretch|Elevated_prayer_stretch
    Exercise_Band_Dorsiflexion|Exercise_Band_Plantarflexion|Extreme_Lat_Stretch|Extreme_Pec_Stretch
    Extreme_Shoulder_Stretch|Finger_Pushup|Fingerboard_20_mm_edge|Foam_Roll_IT_Band
    Foam_Roller_Adductors|Foam_Roller_Anterior_tibialis|Foam_Roller_Iliotibial_band
    Foam_Roller_quadriceps|Forward_shoulder_rotation|Frog_Stretch|Frog_stand|Front_Lever
    Front_Split_Stretch|Front_lever_pull_up|Front_lever_tuck|Front_neck_stretch|Full_Sit_Outs
    Glute_Bridge_Single_Arm_Press|Guided_or_free_meditation|Hamstring_Chokes|Hamstring_Foam_roller
    Hamstring_Kicks|Head_turns|Hercules_Pillars|High_Cable_Cross_Tricep_Extention_NB|Hollow_Hold
    Horizontal_Shoulder_Flexion_Stretch|Horizontal_traction_isometry|Horse_Stance_Side_Splits
    Hyper_Y_W_Combo|Ice_cream_maker|Incline_DB_Y_Raise|Incline_Shoulder_Press_Up|Incline_Static_Hold
    Inverted_Lat_Pull_Down|Isometria_alle_parallele|Isometria_trazioni_impugnatura_inversa
    Kegel_Exercise|Kettlebell_Halo|Kettlebell_Halo_With_Overhead_Extension|Kick_with_Board|Kong_Curl
    Kreis_Press_DB|L_Hold|L_Sit_Foot_Supported|L_Sit_Pull_ups|Lat_Pull_DB
    Left_levator_scapulae_stretch|Left_neck_stretch|Leg_Raises_Standing|Leg_Swings_Front_Back
    Leg_Wheel|Leg_and_hip_stretch|Limber_11|Lying_Dumbbell_Row_SS_Seated_Shrug
    Lying_Rotator_Cuff_Exercise|March_or_jog_in_place|Medicine_ball_booklet_crunch|Mentzer_Pulldown
    Neck_CARs|Neck_extension|Neck_half_circles|Nordic_Curl|Open_Book|Parallel_Bar_Hold|Pike_Push_Ups
    Posterior_Pelvic_Tilt|Prone_Scapular_Retraction_Arms_at_Side|Pull_up_Isometric_Hold|Pullback
    Pullover_Machine|Quad_Sets|Quadruped_Hip_Abduction|Quadruped_thoracic_rotation_left
    Quadruped_thoracic_rotation_right|Reach_ups|Recovery_Bobbing|Recruitment_Pulls
    Rest_for_timed_workouts|Reverse_Nordic_Curl|Right_levator_scapulae_stretch|Right_neck_stretch
    Ring_Support_Hold|Roll_Down|Roll_overs_into_V_sits|Rope_Pullover_row|Rotary_Torso_Machine
    Russian_Push_Ups|SMR_Glutes_lax_ball|Schwimmen|Scorpion_Kick|Seated_Corkscrew
    Seated_Shoulder_Extension_Stretch|Serratus_Wall_Slide_Stretch|Shinbox_IR_Stretch
    Shoulder_Dumbbell_Pendular_Exercise|Shoulder_Y_pull_cable|Shoulder_dislocates
    Side_Kick_Breathing_Kickboard|Side_Slides_Squats|Side_laying_interior_rotation
    Side_lying_External_Rotation|Single_Leg_Hamstring_Stretch|Single_Leg_Soft_Landing_Holds
    Single_leg_BOSU_balance|Single_leg_side_glute_press|Sit_Reach|Sitting_Calf_Stretch_Dorsiflexion
    Ski_Machine|Skydiver_with_arms_in_T_position|Sleeper_Stretch|Sloper_hanging|Snap_Down
    Squat_Sky_Reach_Stretch|Standing_Pancake|Standing_Side_Crunches|Standing_biceps_stretch_left
    Standing_biceps_stretch_right|Straddle_L_Sit|Stroke_and_Roll_Drill|Supine_Hip_Abduction
    Supine_press|Suspended_crossess|TRX_Obliques|TRX_Tricep_Extension|Toe_Taps
    Torso_rotation_stretch|Trap_3_Raise|Trap_press|Triceps_stretch_left|Triceps_stretch_right
    Tuck_L_sit|Tuck_planche|Typewriter_Pull_ups|Upper_Back|Vpushup|W_Raise|Wall_Angels|Wall_Drills
    Wall_Hold_Rotation|Wall_Slides|Wrist_circles|YTWL_Exercise|YTW_Raises|YWTs
    ankle_dorsiflexion_rocks|elbow_lever|explosive_push_ups|punches|walking_bridge
    """
}
