// Generated by scripts/import-exercise-art.swift — do not edit by hand.
// Maps a seeded exercise's `seedID` to its illustrated-art slug, and loads/caches the
// matching path data from the bundled DaGym/Resources/ExerciseArtPaths.zlib.
// Artwork: Bryl Lim, derived from Everkinetic, CC BY-SA 4.0 — see
// DaGym/Resources/ATTRIBUTION-ExerciseArt.txt.

import Foundation
import SwiftUI

/// Looks up the 3-frame illustrated art for a seeded exercise, when we have any.
/// Roughly 172 of our seeded exercises match; the rest return `nil` and
/// callers (`ExerciseArtView`) fall back to the existing glyph/icon treatment.
enum ExerciseArtCatalog {
    /// seedID -> art slug.
    static let slugsBySeedID: [String: String] = [
        "Abdominal_Crunch": "crunch",
        "Arnold_Dumbbell_Press": "arnold-press",
        "Assisted_Pull_Up": "assisted-pull-up",
        "Backward_arm_circles": "arm-circles",
        "Band_Pull_Apart": "band-pull-apart",
        "Banded_Clamshell": "banded-clamshell",
        "Barbell_Bench_Press_-_Medium_Grip": "bench-press",
        "Barbell_Deadlift": "deadlift",
        "Barbell_Glute_Bridge": "barbell-glute-bridge",
        "Barbell_Hip_Thrust": "hip-thrust",
        "Barbell_Shrug": "shrug",
        "Barbell_Squat": "squat",
        "Barbell_Wrist_Curl": "wrist-curl",
        "Battle_Ropes": "battle-ropes",
        "Bear_Crawl_Sled_Drags": "bear-crawl",
        "Belt_Squat": "belt-squat",
        "Bench_Dips": "bench-dip",
        "Bent_Over_Barbell_Row": "barbell-row",
        "Bent_Over_Dumbbell_Rows": "dumbbell-bent-over-row",
        "Bird_Dog": "bird-dog",
        "Bodyweight_Squat": "bodyweight-squat",
        "Box_Handstand_Push_up": "handstand-push-up",
        "Bulgarian_split_squats_left": "bulgarian-split-squat",
        "Burpees": "burpee",
        "Butterfly_Stretch": "butterfly-stretch",
        "Cable_Crunch": "cable-crunch",
        "Cable_Curls": "cable-curl",
        "Cable_Hammer_Curls_-_Rope_Attachment": "rope-hammer-curl",
        "Cable_Rear_Delt_Fly": "rear-delt-fly",
        "Cable_Seated_Lateral_Raise": "cable-lateral-raise",
        "Cable_Tricep_Kickback": "cable-kickback",
        "Cable_pull_through": "cable-pull-through",
        "Calf_Raises_-_With_Bands": "calf-raise",
        "Chair_dips": "chair-dip",
        "Child_s_pose": "childs-pose",
        "Chin-Up": "chin-up",
        "Clamshell": "clamshell",
        "Close-Grip_Barbell_Bench_Press": "close-grip-bench-press",
        "Close-Grip_Front_Lat_Pulldown": "close-grip-lat-pulldown",
        "Cossack_squat": "cossack-squat",
        "Crossbody_Hamstring_Stretch": "hamstring-stretch",
        "Crossbody_Leg_Swings": "leg-swings-stretch",
        "Cycling": "cycling",
        "DB_Wrist_Extension": "wrist-extension",
        "Dead_Bug": "dead-bug",
        "Decline_Barbell_Bench_Press": "decline-bench-press",
        "Decline_Dumbbell_Bench_Press": "decline-dumbbell-press",
        "Decline_Push-Up": "decline-push-up",
        "Dips": "dip",
        "Dips_-_Chest_Version": "chest-dip",
        "Donkey_Calf_Raises": "donkey-calf-raise",
        "Drag_Curl": "drag-curl",
        "Dragon_flag": "dragon-flag",
        "Dumbbell_Bench_Press": "dumbbell-bench-press",
        "Dumbbell_Bicep_Curl": "bicep-curl",
        "Dumbbell_Concentration_Curl": "concentration-curl",
        "Dumbbell_Hip_Thrust": "dumbbell-hip-thrust",
        "Dumbbell_Lunges_Walking": "walking-lunge",
        "Dumbbell_Romanian_Deadlift": "dumbbell-romanian-deadlift",
        "Dumbbell_Shrug": "dumbbell-shrug",
        "Dumbbell_Side_Bend": "dumbbell-side-bend",
        "Dumbbell_Split_Squat": "split-squat",
        "Dumbbell_donkey_kick": "donkey-kick",
        "Dumbbell_farmer_s_carry": "farmer-carry",
        "Dumbbell_sumo_deadlift": "dumbbell-sumo-deadlift",
        "Dynamic_side_plank": "side-plank",
        "EZ-Bar_Curl": "ez-bar-curl",
        "EZ-Bar_Skullcrusher": "skull-crusher",
        "Elliptical": "elliptical",
        "Face_Pull": "face-pull",
        "Fire_Hydrant_Circles": "fire-hydrant",
        "Flutter_Kicks": "flutter-kick",
        "Fly_With_Cable": "cable-fly",
        "Fly_With_Dumbbells": "dumbbell-fly",
        "Front_Barbell_Squat": "front-squat",
        "Front_Cable_Raise": "cable-front-raise",
        "Front_Dumbbell_Raise": "front-raise",
        "Front_Plate_Raise": "plate-front-raise",
        "Glute_Bridge": "glute-bridge",
        "Glute_Kickback_Machine": "machine-glute-kickback",
        "Goblet_Squat": "goblet-squat",
        "Good_Morning": "good-morning",
        "Hack_Squat": "hack-squat",
        "Hammer_Curls": "hammer-curl",
        "Hanging_Leg_Raise": "hanging-leg-raise",
        "High_knees": "high-knees",
        "Hip_Airplane": "hip-airplane",
        "Hyperextensions_Back_Extensions": "back-extension",
        "Incline_Bench_Press_Barbell": "incline-bench-press",
        "Incline_Chest_Supported_Dumbbell_Row": "chest-supported-row",
        "Incline_Dumbbell_Curl": "incline-dumbbell-curl",
        "Incline_Dumbbell_Press": "incline-dumbbell-press",
        "Incline_Push-Up": "incline-push-up",
        "Inverted_Row": "inverted-row",
        "Jump_rope_basic_jumps": "jump-rope",
        "Jumping_Jacks": "jumping-jack",
        "Kettlebell_Swing": "kettlebell-swing",
        "Landmine_Squat_to_Press": "landmine-press",
        "Leg_Extensions": "leg-extension",
        "Leg_Press": "leg-press",
        "Leg_Raises_Lying": "lying-leg-raise",
        "Leverage_Machine_Chest_Press": "machine-chest-press",
        "Lying_Leg_Curls": "leg-curl",
        "Machine_Hip_Abduction": "hip-abduction-machine",
        "Machine_Lateral_Raise": "machine-lateral-raise",
        "Machine_Shoulder_Military_Press": "machine-shoulder-press",
        "Meadows_Row": "meadows-row",
        "Mountain_climbers": "mountain-climber",
        "One-Arm_Dumbbell_Row": "one-arm-dumbbell-row",
        "Overhead_Cable_Tricep_Extension": "overhead-tricep-extension",
        "Pallof_Press": "pallof-press",
        "Pec_Deck": "pec-deck",
        "Pistol_Squat": "pistol-squat",
        "Plank": "plank",
        "Plank_Jacks": "plank-jack",
        "Plank_Shoulder_Taps": "plank-shoulder-tap",
        "Preacher_Curl": "preacher-curl",
        "Pullups": "pull-up",
        "Push-Up_Wide": "wide-push-up",
        "Push_Press": "push-press",
        "Push_Up": "push-up",
        "Rack_Pulls": "rack-pull",
        "Reverse_Crunch": "reverse-crunch",
        "Reverse_Curl": "reverse-curl",
        "Reverse_Hyperextension": "reverse-hyperextension",
        "Reverse_Snow_Angel": "reverse-snow-angel",
        "Reverse_lunges": "reverse-lunge",
        "Romanian_Deadlift": "romanian-deadlift",
        "Rowing_Machine": "rowing",
        "Running_Treadmill": "running",
        "Russian_Twist": "russian-twist",
        "Scapular_Pull-Up": "scapular-pull-up",
        "Seated_Bent-Over_Rear_Delt_Raise": "bent-over-rear-delt-raise",
        "Seated_Cable_Row": "seated-row",
        "Seated_Calf_Raise": "seated-calf-raise",
        "Seated_Knee_Tuck": "seated-knee-tuck",
        "Seated_Leg_Curl": "seated-leg-curl",
        "Seated_Row_Machine": "machine-row",
        "Side_Lateral_Raise": "lateral-raise",
        "Side_Lying_Hip_Abduction": "side-lying-hip-abduction",
        "Single-Leg_High_Box_Squat": "single-leg-box-squat",
        "Single_Leg_Glute_Bridge": "single-leg-glute-bridge",
        "Sliding_Lateral_Lunge": "lateral-lunge",
        "Smith_Machine_Bench_Press": "smith-machine-bench-press",
        "Smith_Machine_Split_Squat": "smith-machine-split-squat",
        "Smith_Machine_Squat": "smith-machine-squat",
        "Spider_Curl": "spider-curl",
        "Squat_Jumps": "jump-squat",
        "Squat_Thrust": "squat-thrust",
        "Standing_Calf_Raises": "standing-calf-raise",
        "Standing_Dumbbell_Press": "standing-dumbbell-press",
        "Standing_Military_Press": "overhead-press",
        "Step-up_with_Knee_Raise": "step-up",
        "Straight-Arm_Pulldown": "straight-arm-pulldown",
        "Sumo_Deadlift": "sumo-deadlift",
        "Superman": "superman",
        "Swimming_50m_sprints": "swimming",
        "T_Bar_row": "t-bar-row",
        "Toe_Touch": "toe-touch",
        "Torso_Twist": "torso-twist-stretch",
        "Trap_Bar_Deadlift": "trap-bar-deadlift",
        "Tricep_Dumbbell_Kickback": "tricep-kickback",
        "Tricep_Rope_Pushdowns": "rope-tricep-pushdown",
        "Triceps_Dips_Assisted": "assisted-dip",
        "Triceps_Pushdown": "tricep-pushdown",
        "Upright_Barbell_Row": "upright-row",
        "Walking": "walking",
        "Wall_sit": "wall-sit",
        "Weighted_Bench_Dip": "weighted-dip",
        "Weighted_Crunch": "weighted-crunch",
        "Weighted_Sissy_Squat": "sissy-squat",
        "Wide-Grip_Lat_Pulldown": "lat-pulldown"
    ]

    /// The art slug for `seedID`'s illustration, or `nil` when this exercise has no
    /// illustrated art. Pass this to `ExerciseArtPathStore` to load the actual frames.
    static func slug(for seedID: String) -> String? {
        slugsBySeedID[seedID]
    }

    /// Existence check kept in its original array-returning shape for callers that only test
    /// this for `!= nil` (the array's contents are not asset names any more — the artwork
    /// itself comes from `ExerciseArtPathStore`, keyed by `slug(for:)`).
    static func frames(for seedID: String) -> [String]? {
        guard let slug = slugsBySeedID[seedID] else { return nil }
        return [slug, slug, slug]
    }
}

/// Loads the bundled, zlib-compressed exercise-art path data (raw SVG `d=` path strings,
/// coordinates rounded to 1 decimal place — see import-exercise-art.swift) and parses each
/// frame into a SwiftUI `Path` on first use, reusing MuscleMap's vendored SVG parser
/// (`DaGym/Vendor/MuscleMap/Core/{SVGPathParser,PathBuilder}.swift`). An `actor` so decoding
/// and parsing run off the main actor, and results are cached in memory for the process
/// lifetime so the same slug is never re-parsed.
actor ExerciseArtPathStore {
    static let shared = ExerciseArtPathStore()

    private var rawFramesBySlug: [String: [String]]?
    private var pathCache: [String: [Path]] = [:]

    /// The three frame `Path`s for `slug` (in a 512×512 coordinate space, matching the
    /// source SVGs' viewBox — callers scale to their display size), in playback order, or
    /// `nil` if `slug` has no bundled path data.
    func frames(forSlug slug: String) -> [Path]? {
        if let cached = pathCache[slug] { return cached }
        guard let raw = loadedRawFrames()[slug] else { return nil }
        let paths = raw.map { PathBuilder.buildPath(from: $0, scale: 1, offsetX: 0, offsetY: 0) }
        pathCache[slug] = paths
        return paths
    }

    private func loadedRawFrames() -> [String: [String]] {
        if let rawFramesBySlug { return rawFramesBySlug }
        let loaded = Self.loadRawFrames()
        rawFramesBySlug = loaded
        return loaded
    }

    private static func loadRawFrames() -> [String: [String]] {
        guard
            let url = Bundle.main.url(forResource: "ExerciseArtPaths", withExtension: "zlib"),
            let compressed = try? Data(contentsOf: url),
            let data = try? (compressed as NSData).decompressed(using: .zlib) as Data,
            let decoded = try? JSONDecoder().decode([String: [String]].self, from: data)
        else { return [:] }
        return decoded
    }
}
